/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.example.hbase;

@SuppressWarnings("all")
/** manual-generated Avro schema for hbase:table1. T_T */
public class Hbase_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Hbase_V1\",\"namespace\":\"com.linkedin.events.example.hbase\",\"fields\":[{\"name\":\"key\",\"type\":[\"bytes\",\"null\"],\"meta\":\"dbFieldName=key;dbFieldPosition=0;\"},{\"name\":\"value\",\"type\":[\"bytes\",\"null\"],\"meta\":\"dbFieldName=value;dbFieldPosition=1;\"}],\"meta\":\"dbFieldName=table1;\"}");
  public java.nio.ByteBuffer key;
  public java.nio.ByteBuffer value;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.nio.ByteBuffer)value$; break;
    case 1: value = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}