/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.example.hbase;

@SuppressWarnings("all")
/** manual-generated Avro schema for hbase:table1. Generated at Dec 04, 2012 05:07:05 PM PST */
public class Hbase_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Hbase_V1\",\"namespace\":\"com.linkedin.events.example.hbase\",\"fields\":[{\"name\":\"cf1\",\"type\":[\"bytes\",\"null\"],\"meta\":\"dbFieldName=cf1;dbFieldPosition=0;\"},{\"name\":\"cf2\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=cf2;dbFieldPosition=1;\"}],\"meta\":\"dbFieldName=table1;\"}");
  public java.nio.ByteBuffer cf1;
  public java.lang.Long cf2;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cf1;
    case 1: return cf2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cf1 = (java.nio.ByteBuffer)value$; break;
    case 1: cf2 = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
